#!/usr/bin/bash
clear

# edit /etc/pacman.conf file
vim /etc/pacman.conf

clear

# disk configuration
lsblk
echo ' '
read -p 'Select disk (Example: vda, sda, nvme0n1): ' disk_selection
cfdisk /dev/$disk_selection

clear
lsblk
echo ' '

# format disk label (ext4)
read -p 'Root partition (Example: vda1, sda1, nvme0n1p1): ' root_partition
mkfs.ext4 /dev/$root_partition
mount /dev/$root_partition /mnt

read -p 'Boot partition (Example: vda1, sda1, nvme0n1p1): ' boot_partition
mkfs.fat -F32 /dev/$boot_partition
mkdir -p /mnt/boot/efi

clear

# format disk label (btrfs)
read -p 'Root partition (Example: vda1, sda1, nvme0n1p1): ' root_partition
mkfs.btrfs /dev/$root_partition
mount /dev/$root_partition /mnt
btrfs sub create /mnt/@
btrfs sub create /mnt/@home
btrfs sub create /mnt/@swap
umount /mnt

mount -o noatime,nodiratime,compress=zstd,commit=120,space_cache,ssd,discard=async,autodefrag,subvol=@ /dev/$root_partition /mnt
mkdir -p /mnt/{boot,home,swap}
mount -o noatime,nodiratime,compress=zstd,commit=120,space_cache,ssd,discard=async,autodefrag,subvol=@home /dev/$root_partition /mnt/@home
mount -o noatime,nodiratime,compress=zstd,commit=120,space_cache,ssd,discard=async,autodefrag,subvol=@home /dev/$root_partition /mnt/@swap

btrfs filesystem mkswapfile --size 4g --uuid clear /swap/swapfile
swapon /swap/swapfile


read -p 'Boot partition (Example: vda1, sda1, nvme0n1p1): ' boot_partition
mkfs.fat -F32 /dev/$boot_partition
mkdir -p /mnt/efi
mount /dev/$root_partition /mnt/efi

clear

# Update the system clock
rc-service ntpd start

clear

# install base packages
read -p 'install packages: ' pacman_packages
basestrap -i /mnt $pacman_packages 

# create fstab file
fstabgen -U /mnt > /mnt/etc/fstab
echo -e "/swap/swapfile none swap defaults 0 0" >> /etc/fstab
mount /dev/$boot_partition /mnt/boot/efi

cp $(pwd)/chroot /mnt
artix-chroot /mnt /bin/bash
rm -rf /mnt/chroot
