#!/usr/bin/bash
clear

# edit /etc/pacman.conf file
vim /etc/pacman.conf

clear

# disk configuration
lsblk
echo ' '
read -p 'Select disk (Example: vda, sda, nvme0n1): ' disk_selection
cfdisk /dev/$disk_selection

clear
lsblk
echo ' '

# format disk label
read -p 'Root partition (Example: vda1, sda1, nvme0n1p1): ' root_partition
mkfs.btrfs /dev/$root_partition
mount /dev/$root_partition /mnt
btrfs sub create /mnt/@artix
btrfs subvolume create /mnt/@home
umount /mnt

mount -o compress=zstd,subvol=@ /dev/$root_partition /mnt
mkdir -p /mnt/home
mount -o compress=zstd,subvol=@home /dev/$root_partition /mnt/home

read -p 'Boot partition (Example: vda1, sda1, nvme0n1p1): ' boot_partition
mkfs.fat -F32 /dev/$boot_partition
mkdir -p /mnt/efi
mount /dev/$root_partition /mnt/efi

clear

# Update the system clock
rc-service ntpd start

clear

# install base packages
basestrap -i /mnt base base-devel linux linux-headers linux-firmware openrc git vim btrfs-progs rsync xdg-user-dirs bluez bluez-openrc bluez-utils \
pipewire pipewire-alsa pipewire-pulse pipewire-jack wireplumber reflector openssh man sudo neovim zsh zsh-completions zsh-autosuggestions zstd \
archlinux-mirrorlist artix-archlinux-support amd-ucode amdgpu mesa vulkan-radeon libva-mesa-driver mesa-vdpau xf86-video-amdgpu 

# create fstab file
fstabgen -U /mnt > /mnt/etc/fstab
mount /dev/$boot_partition /mnt/boot/efi

cp $(pwd)/chroot /mnt
artix-chroot /mnt /bin/bash
rm -rf /mnt/chroot
