#!/usr/bin/bash
clear

# edit /etc/pacman.conf file
# neovim /etc/pacman.conf

cat << EOF >> /etc/pacman.conf
[lib32]
Include = /etc/pacman.d/mirrorlist

# stable arch repos
[extra]
Include = /etc/pacman.d/mirrorlist-arch
[multilib]
Include = /etc/pacman.d/mirrorlist-arch
[community]
Include = /etc/pacman.d/mirrorlist-arch
EOF

pacman-key --populate archlinux

clear

# timezone
echo 'Example: Europe/Istanbul, Europe/Zurich, America/New_York'
read -p 'Timezone: ' time_zone
ln -sf /usr/share/zoneinfo/$time_zone /etc/localtime
hwclock --systohc

clear

# locale

read -p "Select locale [en/tr]: " localeset

if [ $localeset == "en" ];
then
    echo "en_US.UTF-8" >> /etc/locale.gen
    locale-gen
    touch /etc/locale.conf
    echo "LANG=en_US.UTF-8" >> /etc/locale.conf
else
    echo "tr_TR.UTF-8" >> /etc/locale.gen
    locale-gen
    touch /etc/locale.conf
    echo "LANG=tr_TR.UTF-8" >> /etc/locale.conf
fi

clear

# host
read -p 'Hostname: ' host_name
echo $host_name >> /etc/hostname

echo '127.0.0.1       localhost' >> /etc/hosts
echo '::1             localhost' >> /etc/hosts
echo '127.0.1.1       '$host_name'.localdomain     '$host_name >> /etc/hosts

clear

# root password
echo 'Root password'
passwd
sleep 2

clear

# packages
pacman -Sy networkmanager networkmanager-openrc
sleep 2
clear

rc-update add NetworkManager default
sleep 2
clear

# DHCP client
pacman -S dhcpcd
sleep 2
clear

pacman -S connman-openrc connman-gtk
rc-update add connmand

# NTFS filesystem support
pacman -S ntfs-3g
sleep 2
clear

# GRUB
#pacman -S grub efibootmgr os-prober
#sleep 2
#clear

#grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id='Artix Linux'
#sleep 2
#clear

#grub-mkconfig -o /boot/grub/grub.cfg
#sleep 2
#clear

# REFIND
pacman -S refind efibootmgr
sleep 2
clear

refind-install
sleep 2
clear

# useradd
read -p 'Username: ' user_name
useradd -m -g users -G wheel,storage,power,audio,video -s /bin/bash $user_name
clear

echo $user_name 'password'
passwd $user_name
sleep 2

# sudo privileges
EDITOR=neovim visudo
clear
